// Generated by CoffeeScript 1.9.3
(function() {
  var ScriptParser, script, yaml;

  yaml = require('yamljs');

  ScriptParser = require('./app/services/scriptParser/ScriptParser');

  script = yaml.load('./app/services/scriptParser/example.yml');

  new ScriptParser(script);

}).call(this);
